---
- name: Download Damn Vulnerable Web Application
  get_url:
    url: https://github.com/RandomStorm/DVWA/archive/v1.9.zip
    dest: /tmp/dvwa-1.9.zip

- name: Unarchive Damn Vulnerable Web Application
  unarchive:
    src: /tmp/dvwa-1.9.zip
    dest: /tmp
    copy: no

- name: Remove default /var/www
  file:
    path: /var/www
    state: absent

- name: Move Damn Vulnerable Web Application files to /var/www
  command: /bin/mv /tmp/DVWA-1.9 /var/www

- name: Cleanup downloaded .zip file
  file:
    path: /tmp/dvwa-1.9.zip
    state: absent

- name: Modify MySQL password in Damn Vulnerable Web Application configuration file
  lineinfile:
    dest: /var/www/config/config.inc.php
    regexp: "$_DVWA[ 'db_password' ] = 'p@ssw0rd';"
    line: "$_DVWA[ 'db_password' ] = '';"
    
- name: Set permissions for /var/www
  file:
    path: /var/www
    owner: www-data
    group: www-data
    recurse: yes

- name: Modify php.ini for Apache
  lineinfile:
    dest: /etc/php5/apache2/php.ini
    regexp: "allow_url_include = Off"
    line: "allow_url_include = On"

- name: Restart Apache
  service:
    name: apache2
    state: restarted
