---
- name: Download Damn Vulnerable Web Application
  get_url:
    url: https://github.com/RandomStorm/DVWA/archive/v1.9.zip
    dest: /tmp/dvwa-1.9.zip

- name: Unarchive Damn Vulnerable Web Application
  unarchive:
    src: /tmp/dvwa-1.9.zip
    dest: /tmp
    copy: no

- name: Remove default /var/www
  file:
    path: /var/www
    state: absent

- name: Move Damn Vulnerable Web Application files to /var/www
  command: /bin/mv /tmp/DVWA-1.9 /var/www

- name: Set permissions for /var/www
  file:
    path: /var/www
    owner: www-data
    group: www-data
    recurse: yes
